import { useTranslation } from 'react-i18next';
import { PermissionEnum } from './enums/permission.enums';

const MENU_ITEMS = () => {
    const { t } = useTranslation();
    return [
        {
            key: 'products',
            label: t('products'),
            isTitle: false,
            icon: 'dripicons-weight',
            routePermission: 'ALL',
            children: [
                {
                    key: 'products',
                    label: t('products'),
                    url: '/products',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
                {
                    key: 'category',
                    label: t('category'),
                    url: '/products/categories',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
                {
                    key: 'unit',
                    label: t('unit'),
                    url: 'products/units',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
                {
                    key: 'manufacturer',
                    label: t('manufacturer'),
                    url: '/products/manufacturers',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
                {
                    key: 'warranty',
                    label: t('warranty'),
                    url: '/products/warranties',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
                {
                    key: 'stock',
                    label: t('stock'),
                    url: '/stock',
                    parentKey: 'products',
                    routePermission: 'ALL',
                },
            ],
        },
        { key: 'contacts', label: t('contacts'), isTitle: true },
        {
            key: 'people',
            label: t('People'),
            isTitle: false,
            icon: 'dripicons-user',
            routePermission: 'ALL',
            children: [
                {
                    key: 'suppliers',
                    label: t('suppliers'),
                    isTitle: false,
                    icon: 'uil-briefcase',
                    url: '/suppliers',
                    parentKey: 'people',
                    routePermission: PermissionEnum.READ_SUPPLIERS,
                },
                {
                    key: 'customers',
                    label: t('customers'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/customers',
                    parentKey: 'people',
                    routePermission: PermissionEnum.READ_CUSTOMERS,
                },
                {
                    key: 'billers',
                    label: t('billers'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/billers',
                    parentKey: 'people',
                    routePermission: 'ALL',
                },
            ],
        },

        { key: 'contacts', label: t('contacts'), isTitle: true },
        {
            key: 'Expenditure',
            label: t('expenditure'),
            isTitle: false,
            icon: 'dripicons-weight',
            routePermission: 'ALL',
            children: [
                {
                    key: 'costSection',
                    label: t('cost section'),
                    url: '/costSections',
                    parentKey: 'Expenditure',
                    routePermission: 'ALL',
                },
                {
                    key: 'expenditure',
                    label: t('expenditure'),
                    url: '/expenditure',
                    parentKey: 'Expenditure',
                    routePermission: 'ALL',
                },
            ],
        },
        { key: 'contacts', label: t('contacts'), isTitle: true },
        {
            key: 'Messages',
            label: t('message'),
            isTitle: false,
            icon: 'uil-comment-alt-dots',
            url: '/messages/inbox',
            routePermission: 'ALL',
        },
        { key: 'permissions', label: 'permissions', isTitle: true },
        {
            key: 'permissions',
            label: t('permissions'),
            isTitle: false,
            icon: 'uil-shield-exclamation',
            routePermission: 'ALL',
            children: [
                {
                    key: 'user-role',
                    label: t('user role'),
                    url: '/user-role',
                    parentKey: 'permissions',
                    routePermission: 'ALL',
                },
                {
                    key: 'permission',
                    label: t('permissions'),
                    url: '/permissions',
                    parentKey: 'permissions',
                    routePermission: 'ALL',
                },
            ],
        },
        { key: 'media', label: 'media', isTitle: true },
        {
            key: 'media',
            label: t('media'),
            isTitle: false,
            icon: 'dripicons-photo',
            routePermission: 'ALL',
            children: [
                {
                    key: 'media',
                    label: t('media'),
                    url: '/media',
                    parentKey: 'media',
                    routePermission: 'ALL',
                },
                {
                    key: 'upload',
                    label: t('upload'),
                    url: '/media/upload',
                    parentKey: 'media',
                    routePermission: 'ALL',
                },
            ],
        },
        { key: 'HRM', label: 'HRM', isTitle: true },
        {
            key: 'HRM',
            label: t('HRM'),
            isTitle: false,
            icon: 'dripicons-user',
            routePermission: 'ALL',
            children: [
                {
                    key: 'department',
                    label: t('Department'),
                    isTitle: false,
                    icon: 'uil-briefcase',
                    url: '/department',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'employee',
                    label: t('Employee'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/employees',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'attendance',
                    label: t('attendance'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/attendance',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'payroll',
                    label: t('payroll'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/payroll',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'holiday',
                    label: t('holiday'),
                    isTitle: false,
                    icon: 'uil-users-alt',
                    url: '/holiday',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'hrmsetting',
                    label: t('HRM Setting'),
                    isTitle: false,
                    icon: 'dripicons-gear',
                    url: '/hrmSetting',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                },
                {
                    key: 'accounts',
                    label: t('accounts'),
                    isTitle: false,
                    icon: 'dripicons-gear',
                    parentKey: 'HRM',
                    routePermission: 'ALL',
                    children: [
                        {
                            key: 'accounts',
                            label: t('accounts'),
                            isTitle: false,
                            icon: 'dripicons-gear',
                            url: '/accounts',
                            parentKey: 'accounts',
                            routePermission: 'ALL',
                        },
                        {
                            key: 'money transfer',
                            label: t('money transfer'),
                            isTitle: false,
                            icon: 'dripicons-gear',
                            url: '/money-transfer',
                            parentKey: 'accounts',
                            routePermission: 'ALL',
                        },
                        {
                            key: 'account statement',
                            label: t('account statement'),
                            isTitle: false,
                            icon: 'dripicons-gear',
                            url: '/account-statement',
                            parentKey: 'accounts',
                            routePermission: 'ALL',
                        },
                    ],
                },
            ],
        },

        { key: 'settings', label: 'settings', isTitle: true },
        {
            key: 'settings',
            label: t('settings'),
            isTitle: false,
            icon: 'dripicons-gear',
            routePermission: 'ALL',
            children: [
                {
                    key: 'user',
                    label: t('users'),
                    url: '/staffs',
                    parentKey: 'settings',
                    routePermission: 'ALL',
                },
                {
                    key: 'ui',
                    label: t('ui'),
                    url: '/settings/ui',
                    parentKey: 'settings',
                    routePermission: 'ALL',
                },
            ],
        },
    ];
};

export default MENU_ITEMS;
