export const PermissionEnum = {
    READ_USERS: 'readUsers',
    CREATE_USER: 'createUser',
    UPDATE_USER: 'updateUser',
    DELETE_USER: 'deleteUser',

    READ_PROPRIETOR: 'readProprietor',
    CREATE_PROPRIETOR: 'createProprietor',
    UPDATE_PROPRIETOR: 'updateProprietor',
    DELETE_PROPRIETOR: 'deleteProprietor',

    CATEGORIES: 'categories',
    READ_CATEGORIES: 'readCategories',
    CREATE_CATEGORY: 'createCategory',
    UPDATE_CATEGORY: 'updateCategory',
    DELETE_CATEGORY: 'deleteCategory',

    SUB_CATEGORIES: 'subcategories',
    READ_SUBCATEGORIES: 'readSubCategories',
    CREATE_SUBCATEGORIES: 'createSubCategories',
    UPDATE_SUBCATEGORIES: 'updateSubCategories',
    DELETE_SUBCATEGORIES: 'deleteSubCategories',

    UNIT: 'unit',
    READ_UNITS: 'readUnits',
    CREATE_UNIT: 'createUnit',
    UPDATE_UNIT: 'updateUnit',
    DELETE_UNIT: 'deleteUnit',

    MANUFACTURERS: 'manufacturers',
    READ_MANUFACTURERS: 'readManufacturers',
    CREATE_MANUFACTURER: 'createManufacturer',
    UPDATE_MANUFACTURER: 'updateManufacturer',
    DELETE_MANUFACTURER: 'deleteManufacturer',

    WARRANTY: 'warranty',
    READ_WARRANTIES: 'readWarranties',
    CREATE_WARRANTY: 'createWarranty',
    UPDATE_WARRANTY: 'updateWarranty',
    DELETE_WARRANTY: 'deleteWarranty',

    SUPPLIER: 'supplier',
    READ_SUPPLIERS: 'readSuppliers',
    CREATE_SUPPLIER: 'createSupplier',
    UPDATE_SUPPLIER: 'updateSupplier',
    DELETE_SUPPLIER: 'deleteSupplier',

    CUSTOMER: 'customer',
    READ_CUSTOMERS: 'readCustomers',
    CREATE_CUSTOMER: 'createCustomer',
    UPDATE_CUSTOMER: 'updateCustomer',
    DELETE_CUSTOMER: 'deleteCustomer',

    COST_SECTIONS: 'costSections',
    READ_COST_SECTIONS: 'readCostSections',
    CREATE_COST_SECTION: 'createCostSection',
    UPDATE_COST_SECTIONS: 'updateCostSections',
    DELETE_COST_SECTIONS: 'deleteCostSections',

    EXPENDITURES: 'expenditures',
    READ_EXPENDITURES: 'readExpenditures',
    CREATE_EXPENDITURE: 'createExpenditure',
    UPDATE_EXPENDITURE: 'updateExpenditure',
    DELETE_EXPENDITURE: 'deleteExpenditure',

    STAFF: 'staff',
    READ_STAFFS: 'readStaffs',
    CREATE_STAFF: 'createStaff',
    UPDATE_STAFF: 'updateStaff',
    DELETE_STAFF: 'deleteStaff',
    READ_LEDGER: 'readLedger',

    UPLOAD_FILE: 'uploadFile',
    READ_FILE: 'readFile',
    DELETE_FILE: 'deleteFile',

    READ_PRODUCT: 'readProduct',
    CREATE_PRODUCT: 'createProduct',
    UPDATE_PRODUCT: 'updateProduct',
    DELETE_PRODUCT: 'deleteProduct',

    READ_ROLE: 'readRole',
    CREATE_ROLE: 'createRole',
    UPDATE_ROLE: 'updateRole',
    DELETE_ROLE: 'deleteRole',

    READ_BRAND: 'readBrand',
    CREATE_BRAND: 'createBrand',
    UPDATE_BRAND: 'updateBrand',
    DELETE_BRAND: 'deleteBrand',

    DEPARTMENT: 'DEPARTMENT',
    READ_DEPARTMENT: 'readDepartment',
    CREATE_DEPARTMENT: 'createDepartment',
    UPDATE_DEPARTMENT: 'updateDepartment',
    DELETE_DEPARTMENT: 'deleteDepartment',

    LEAVETYPES: 'LeaveTypes',
    READ_LEAVETYPES: 'readLeaveTypes',
    CREATE_LEAVETYPE: 'createLeaveType',
    UPDATE_LEAVETYPE: 'updateLeaveType',
    DELETE_LEAVETYPE: 'deleteLeaveType',

    LEAVES: 'LEAVES',
    READ_LEAVES: 'readLeaves',
    CREATE_LEAVE: 'createLeave',
    UPDATE_LEAVE: 'updateLeave',
    DELETE_LEAVE: 'deleteLeave',
};
